name: Sunday
options:
  bundleIdPrefix: it.sunday
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: it.sunday.app
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: "L3N5LHJD5Y"
targets:
  Sunday:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - path: Resources/Assets.xcassets
        type: folder
        buildPhase: resources
      - path: Resources/Sunday.entitlements
        buildPhase: none
    info:
      path: Resources/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        NSLocationWhenInUseUsageDescription: "Sunday needs your location to determine UV levels at your current position"
        NSLocationAlwaysAndWhenInUseUsageDescription: "Sunday needs your location to track UV exposure throughout the day"
        NSHealthShareUsageDescription: "Sunday reads your health data to provide personalized vitamin D recommendations"
        NSHealthUpdateUsageDescription: "Sunday saves your vitamin D intake data to Health app"
        UIUserInterfaceStyle: Light
        NSUserNotificationCenterUsageDescription: "Sunday sends reminders when the sun rises and sets to help you track vitamin D"
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            CFBundleIconName: AppIcon
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "Sources"
        CODE_SIGN_ENTITLEMENTS: Resources/Sunday.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    capabilities:
      - com.apple.HealthKit
      - com.apple.BackgroundModes:
          enabled: true
          modes:
            - location
